
#
# make defines
#

# cc tags

ELGIN_LIBDIR="\"/usr/local/src/pw_elgin/pw_elgin-devel/\""
#static#ELGIN_LIBDIR="\"./\""

CFLAGS= -O -Wall -g  -DLIBDIR=$(ELGIN_LIBDIR) -DHAVE_READLINE


LDFLAGS= -lreadline -lm
CC=gcc


#
# files to make
#
REBUILD_FILES= pw_elgin

# source modules
FILES =	pw_elgin.o 

#
# make definitions
#


all:	Muncmprs Mkupdt


#
# definitions for the modules
#

Mkupdt: $(REBUILD_FILES)
	touch $@

pw_elgin: $(FILES)
	$(CC) -o pw_elgin $(LDFLAGS) $(FILES) $(LIBS)

#
# standard entry names for make
#

clean:	
	-rm -f *.o *.bep *.bpd *.bcs *.bes

rebuild:
	-rm -f Mk* *.t* *.bep *.bpd *.bcs *.bes $(REBUILD_FILES)
	make all

depends:
	make_dep

compress:	Mcmprs

uncompress:	Muncmprs

Mcmprs:
	-compress *.c *.h *.bpl *.s
	-rm -f Muncmprs
	touch $@

Muncmprs:
	-uncompress *.Z
	-rm -f Mcmprs
	touch $@

shar:
	shar Makefile $(HDRS) $(SRCS) > etool.shar

# the following lines were generated by "depends" and should not be modified


# the above lines were generated by "depends" and should not be modified
